export const PODCASTS = [
  {
    id: '1',
    title: 'The Power of Vulnerability',
    source: 'TED Talk',
    duration: '20 min',
    url: 'https://www.ted.com/talks/brene_brown_the_power_of_vulnerability',
    thumbnail: 'https://images.unsplash.com/photo-1518063319789-7217e6706b04?q=80&w=400&auto=format&fit=crop',
    tags: ['mindset', 'wellbeing'],
  },
  {
    id: '2',
    title: 'Why we sleep',
    source: 'The Daily',
    duration: '25 min',
    url: 'https://www.nytimes.com/2020/01/24/podcasts/the-daily/sleep.html',
    thumbnail: 'https://images.unsplash.com/photo-1541480601022-2308c0f02487?q=80&w=400&auto=format&fit=crop',
    tags: ['health', 'productivity'],
  },
  {
    id: '3',
    title: 'Atomic Habits',
    source: 'James Clear',
    duration: '15 min',
    url: 'https://jamesclear.com/atomic-habits',
    thumbnail: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?q=80&w=400&auto=format&fit=crop',
    tags: ['habits', 'growth'],
  },
  {
    id: '4',
    title: 'How to be Happy',
    source: 'Ten Percent Happier',
    duration: '45 min',
    url: 'https://www.tenpercent.com/podcast',
    thumbnail: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=400&auto=format&fit=crop',
    tags: ['mindfulness', 'happiness'],
  },
  {
    id: '5',
    title: 'Deep Work',
    source: 'Cal Newport',
    duration: '30 min',
    url: 'https://www.calnewport.com/podcast/',
    thumbnail: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?q=80&w=400&auto=format&fit=crop',
    tags: ['focus', 'work'],
  },
];
